all:
clean:
	find -iname \*\~ -exec rm -rf {} \;
	find -iname \*.backup -exec rm -rf {} \;
	find -iname \*.log -exec rm -rf {} \;
	find -iname \*.aux -exec rm -rf {} \;
	find -iname ppgec.pdf -exec rm -rf {} \;
	find -iname \*.backup -exec rm -rf {} \;
	find -iname \*.bbl -exec rm -rf {} \;
	find -iname \*.blg -exec rm -rf {} \;
	find -iname \*.toc -exec rm -rf {} \;
	find -iname \*.nlo -exec rm -rf {} \;
	find -iname \*.lof -exec rm -rf {} \;
	find -iname \*.lot -exec rm -rf {} \;
